### ISSUE TITLE
Query for array of objects

### ISSUE THREAD

**Issue by amitjain28** [automategreen/dynamoose#220]
i am having following schema.

```
var dynamoose = require('dynamoose');
var UserSchema = new dynamoose.Schema({
    userId: {
      hashKey: true,
      type: String
    },
    creationTime : {
      rangeKey : true,
      type : Number
    },
  first_name: {
      type: String
  },
  last_name: {
      type: String
  },
  device_info: [{
      device_id: {type: String, default: null},
      access_token: {type: String, default: null}
  }],
  is_active: {
      type: Boolean,
      default: true
  },
  blogs: []
   },  {
       useNativeBooleans: true,
       useDocumentTypes: true,
       timestamps: {
         createdAt: 'creation_at',
         updatedAt: 'updated_at'
       }
});

exports = dynamoose.model('Users', UserSchema);

```

here i want to fetch data based on access_token.
means i have used following code while i have used mongoose (mongodb)

> User.findOne({'device_info.access_token': '12345'})
>   .exec(function (err, users) {
>     res.json(users);
>   });

How can i use this query in dynamoose(dynamo db)

**Comment by brandongoode** [comment]
You'll need to use a `FilterExpression` for a nested value.

```js
var filter = {
  FilterExpression: 'device_info.access_token = :token',
  ExpressionAttributeValues: {
    ':token': '12345'
  }
};

User.scan(filter).exec()
  .then(users => console.log(users))
  .catch(err => console.error(err));
```

**Comment by amitjain28** [comment]
This solution is not working. Showing ScanError: Invalid comparison %s error

```
ScanError: Invalid comparison %s
    at Scan.compVal (D:\2017\test\dummy\node_modules\dynamoose\lib\Scan.js:214:11)
    at Scan.parseFilterObject (D:\2017\test\dummy\node_modules\dynamoose\lib\Scan.js:164:16)
    at new Scan (D:\2017\test\dummy\node_modules\dynamoose\lib\Scan.js:26:10)
    at Function.Model.scan (D:\2017\test\dummy\node_modules\dynamoose\lib\Model.js:663:14)
    at Function.NewModel.scan (D:\2017\test\dummy\node_modules\dynamoose\lib\Model.js:95:18)
    at exports.getSingleUsers (D:\2017\test\dummy\controller.js:97:11)
    at Layer.handle [as handle_request] (D:\2017\test\dummy\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\2017\test\dummy\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\2017\test\dummy\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\2017\test\dummy\node_modules\express\lib\router\layer.js:95:5)
```
