### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Onnion** [automategreen/dynamoose#248]
**I created the following schema:**
```javascript
// Create CacheSearch Schema
const CacheSearch = new dynamoose.Schema({
    updated_at: {
        type: String,
        required: false,
    },
    created_at: {
        type: String,
        required: true,
        rangeKey: true
    },
    cache_id: {
        type: String,
        hashKey: true,
        required: true
    },
    uses: {
        type: Number,
        required: true,
        default: 1
    },
    search: {
        type: Object
    },
    flights: [Object],
    flights_back: [Object]
},{ useDocumentTypes: true, useNativeBooleans: true});

// end Create CacheSearch Schema
```

**I inserted the data from Aws `console**
![screenshot-2017-11-28 dynamodb aws console](https://user-images.githubusercontent.com/19847360/33343889-b8aaeb60-d465-11e7-8f7c-860cca779f52.png)

**But when I tried to use the .scan ()  i received the following error log in the**
```javascript
CacheSearch.scan().exec()
        .then( (res) => {
            console.log(res);
        }).catch(err => {console.error(err)})
```

```console
TypeError: Cannot read property 'map' of undefined
at dedynamofy (/var/www/crawler/node_modules/dynamoose/lib/Attribute.js:419:17)
at Attribute.parseDynamo (/var/www/crawler/node_modules/dynamoose/lib/Attribute.js:498:13)
at Schema.parseDynamo (/var/www/crawler/node_modules/dynamoose/lib/Schema.js:182:24)
at toModel (/var/www/crawler/node_modules/dynamoose/lib/Scan.js:58:12)
at Array.map (<anonymous>)
at Response.<anonymous> (/var/www/crawler/node_modules/dynamoose/lib/Scan.js:211:35)
at Request.<anonymous> (/var/www/crawler/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/www/crawler/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/www/crawler/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/www/crawler/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/www/crawler/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/www/crawler/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/www/crawler/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/www/crawler/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/www/crawler/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/www/crawler/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/var/www/crawler/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/www/crawler/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/www/crawler/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/www/crawler/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/www/crawler/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/www/crawler/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/www/crawler/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/www/crawler/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/var/www/crawler/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/www/crawler/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/www/crawler/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/www/crawler/node_modules/aws-sdk/lib/state_machine.js:14:12)
```

**Comment by fishcharlie** [comment]
@Onnion Can you provide those two items you imported into your table so we can debug better?

**Comment by brandongoode** [comment]
@Onnion Also, could you rerun the test with the latest from the master branch.  There have been several changes to Attribute.js to fix some issues.  Thanks

**Comment by mtso** [comment]
I also got the same error message. I first created a new item by hand in the AWS console, then tried to match up the dynamoose Model with the data. The value of the field that throws an error was set to a `List` of `Map` elements in the console when I created the item.

### System
```
node v8.6.0
dynamoose ^0.8.6
```
### Model Definition
```js
const Test = dynamoose.model('ToyApi-Test', {
  id: {
    type: String,
    hashKey: true,
  },
  name: {
    type: String,
  },
  order: {
    type: Number,
    index: {
      global: true,
      throughput: 1,
      name: 'order-index',
      project: true,
    },
  },
  tests: {
    type: [Object], // Mis-matched data type?
  },
})
```

### Trace
```sh
/home/app/src/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'map' of undefined
    at dedynamofy (/home/app/src/node_modules/dynamoose/lib/Attribute.js:419:17)
    at Attribute.parseDynamo (/home/app/src/node_modules/dynamoose/lib/Attribute.js:498:13)
    at Schema.parseDynamo (/home/app/src/node_modules/dynamoose/lib/Schema.js:182:24)
    at Response.<anonymous> (/home/app/src/node_modules/dynamoose/lib/Model.js:400:14)
    at Request.<anonymous> (/home/app/src/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/home/app/src/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/app/src/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/app/src/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/app/src/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/app/src/node_modules/aws-sdk/lib/state_machine.js:14:12)
```

### Query
```js
Test
  .query('order')
  .eq(1)
  .exec()
  .then((res) => {
    console.log(res)
  })
  .catch(console.error)
```

### Model Update
```js
  tests: {
    type: String, // No error thrown
  },
```

### Result After Datatype Update
```
[ NewModel {
    order: 1,
    id: '720ae023-ce1a-4532-adaf-20f81113bf52',
    name: 'sum-api',
    tests: '{"L":[{"M":{"request":{"M":{"path":{"S":"/1/2/3"},"header":{"M":{"Content-Type":{"S":"text/html, application/json"}}},"method":{"S":"GET"},"query":{"M":{}}}},"description":{"S":"should respond with sum of path integers"},"response":{"M":{"body":{"S":"6"},"code":{"N":"200"}}}}}]}' },
  lastKey: undefined,
  count: 1,
  scannedCount: 1 ]
```
