### ISSUE TITLE
Timestamp Index

### ISSUE THREAD

**Issue by fishcharlie** [automategreen/dynamoose#296]
I'm getting the following error in my code when I try to scan a table that has a index that has a `Sort Index` for the property `createdAt`.

Is there any reason for this happening and how to fix it?

```
ValidationException: One or more parameter values were invalid: Type mismatch for Index Key createdAt Expected: S Actual: N IndexName: url-createdAt-index-1
    at Request.extractError (/home/ubuntu/node/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/home/ubuntu/node/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/ubuntu/node/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/ubuntu/node/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ubuntu/node/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/ubuntu/node/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/ubuntu/node/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by fishcharlie** [comment]
@nbarnett Is this a duplicate of #226, or not?

**Comment by nbarnett** [comment]
I don't think so. It's been a little while, but from memory #226 was specific to an issue with `updatedAt` but was fine with using `createdAt`. This issue looks like its to do with the type associated with `createdAt`. `Expected: S Actual: N` makes me think that `createdTime` is being stored as an ISO string, but is being passed a UNIX timestamp

**Comment by fishcharlie** [comment]
@nbarnett Ok thanks! Maybe @brandongoode will have ideas about this.

**Comment by Tirke** [comment]
Hello @fishcharlie what's the status on this one? We are currently seeing it in one of our model with a global index with `createdAt` as the range key.
