### ISSUE TITLE
ValidationException: Query condition missed key schema element: local

### ISSUE THREAD

**Issue by rawsh** [automategreen/dynamoose#353]
Not sure where this is happening since the debug is just this:

```
ValidationException: Query condition missed key schema element: local
    at Request.extractError (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/environment/easy-node-authentication/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-usK
```

**Comment by rawsh** [comment]
Might be this:

```
User.queryOne({ 'local_email' :  {eq: email} }, function(err, user) {
                // if there are any errors, return the error
                if (err)
                    return done(err);

                // if no user is found, return the message
                if (!user)
                    return done(null, false, req.flash('loginMessage', 'No user found.'));

                if (!user.validPassword(password))
                    return done(null, false, req.flash('loginMessage', 'Oops! Wrong password.'));

                // all is well, return user
                else
                    return done(null, user);
            });
```

Is local_email a valid key name?

**Comment by fishcharlie** [comment]
@rawsh `local_email` should be a valid key name. Is the call back function returning an `err` in there?

**Comment by rawsh** [comment]
@fishcharlie I actually fixed this by deleting the table. I think a record was malwritten

**Comment by rawsh** [comment]
@fishcharlie thanks for the replies

**Comment by fishcharlie** [comment]
@rawsh Awesome. Glad it's working now!!
