### ISSUE TITLE
DynamoDB Local HTTPS Error

### ISSUE THREAD

**Issue by fishcharlie** [automategreen/dynamoose#64]
I keep getting the following error when trying to run DynamoDB locally. Looks like the tests Dynamoose run just fine and run DynamoDB locally as well. So I'm not sure why it would be giving me this error here. Any ideas?

```
dynamoose:table error describing table +26s { NetworkingError: Protocol "http:" not supported. Expected "https:"
  at new ClientRequest (_http_client.js:55:11)
  at Object.exports.request (http.js:31:10)
  at handleRequest (/Code/node_modules/aws-sdk/lib/http/node.js:43:23)
  at executeSend (/Code/node_modules/aws-sdk/lib/event_listeners.js:241:29)
  at Request.SEND (/Code/node_modules/aws-sdk/lib/event_listeners.js:256:9)
  at Request.callListeners (/Code/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
  at Request.emit (/Code/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/Code/node_modules/aws-sdk/lib/request.js:661:14)
  at Request.transition (/Code/node_modules/aws-sdk/lib/request.js:22:10)
  at AcceptorStateMachine.runTo (/Code/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /Code/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/Code/node_modules/aws-sdk/lib/request.js:38:9)
  at Request.<anonymous> (/Code/node_modules/aws-sdk/lib/request.js:663:12)
  at Request.callListeners (/Code/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  at callNextListener (/Code/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
  at /Code/node_modules/aws-sdk/lib/event_listeners.js:167:9
message: 'Protocol "http:" not supported. Expected "https:"',
code: 'NetworkingError',
region: 'us-west-2',
hostname: 'localhost',
retryable: true,
time: 2016-09-12T04:47:32.910Z }
```

**Comment by shengt** [comment]
Got the same error here. How do you fix it?

**Comment by henhal** [comment]
I got the very same issue and it turns out it was my `httpOptions` used to resolve https://github.com/aws/aws-sdk-js/issues/862 that caused the problems. These options set up an HTTPS agent with TLSv1, and as a side-effect apparently disables HTTP.

Details:

This does NOT work (gives the "http not supported" message):

```
new AWS.DynamoDB({
  endpoint: new AWS.Endpoint('http://localhost:8000'),
  httpOptions: {
    agent: new https.Agent({
      secureProtocol: "TLSv1_method",
      ciphers: "ALL"
    })
  }
});
```

but this works:

```
new AWS.DynamoDB({
  endpoint: new AWS.Endpoint('http://localhost:8000')
});
```

The sneaky thing was I had the `httpOptions` injected as default options in one central place to eliminate the 862 issue and didn't immediately realize what was happening - when setting up a DynamoDB object from a stand-alone node console everything was working fine! :)
